services:
  mongodb:
    image: mongo:7-jammy
    container_name: devportal-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: devportal
      MONGO_INITDB_ROOT_PASSWORD: devportal
      MONGO_INITDB_DATABASE: devportal
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: devportal-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:4.0
    container_name: devportal-localstack
    environment:
      SERVICES: s3,sqs
      DEFAULT_REGION: us-east-1
      LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT: 1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodata:
